// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ublorjgvkgbiojihardt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVibG9yamd2a2diaW9qaWhhcmR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NzgyMzMsImV4cCI6MjA1MzE1NDIzM30.EEZYWoa2SAlV34byEso72vsltrr6EN443MAtKR5PrVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);